### ISSUE TITLE
Inotify stream API doesn't seem to work well when watching a file directly.

### ISSUE THREAD

**Issue by llacroix** [hannobraun/inotify#150]
When trying to watch files using a path as &str that points directly to a file

After modifying the file with Mask to ALL_EVENTS,

I only get those 4 events:

```
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: MOVE_SELF, cookie: 0, name: None }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: ATTRIB, cookie: 0, name: None }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: DELETE_SELF, cookie: 0, name: None }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: IGNORED, cookie: 0, name: None }
```

Then any modification to the file doesn't trigger any event. I could be wrong but it seems that from those events, inotify watch a file and when I save it, the file gets "deleted". I'm saving with vim, so it could be possible as it's more or less exchanging file with a swap file.

Here's a complete log when logging directory.

```
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: CREATE, cookie: 0, name: Some("4913") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: OPEN, cookie: 0, name: Some("4913") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: ATTRIB, cookie: 0, name: Some("4913") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: CLOSE_WRITE, cookie: 0, name: Some("4913") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: DELETE, cookie: 0, name: Some("4913") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: MOVED_FROM, cookie: 810220, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: MOVED_TO, cookie: 810220, name: Some("config.json~") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: CREATE, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: OPEN, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: MODIFY, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: ATTRIB, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: CLOSE_WRITE, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: ATTRIB, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: DELETE, cookie: 0, name: Some("config.json~") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: OPEN, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: CLOSE_NOWRITE, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: OPEN, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: CLOSE_NOWRITE, cookie: 0, name: Some("config.json") }
event: Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: MODIFY, cookie: 0, name: Some(".config.json.swp") }
```

I can't say exactly if its a bug as watching the file probably watch changes until the fd is dead... But shouldn't it watch in case the file gets created too? Watching the folder is probably my best solution as in theory none of the other file should get updated other than config files and filtering on the name should be fairly easy.

**Comment by hannobraun** [comment]
Hi @llacroix, thanks for the report!

I don't think this is a bug in this library. I agree that vim is probably replacing the file when saving (I think that's best practice, as you could otherwise get a corrupted file, if the power goes out or something). I see how this is inconvenient for you, and why you would like to have a different behavior. But I don't think this is something that should be handled in the `inotify` crate. This is just a wrapper around inotify, so I don't think we should be changing its behavior too much.

I agree that watching the directory and filtering by name would be a good option. Maybe you can even build a small library on top of `inotify` to handle this. I'd be happy to link to such a crate from the README. Alternatively, you can take a look at [`notify`](https://crates.io/crates/notify), which is a cross-platform abstraction that uses the `inotify` crate on Linux. I don't know how they handle this, but maybe they have a solution already.

I'm going to close this issue, but feel free to re-open it, if you disagree.

**Comment by llacroix** [comment]
I ended up watching the directory. It just it wasn't very obvious at first that the watching a file watches a file descriptor and track its wherever it end up if it gets renamed/moved but if the name change for something else, it doesn't suddenly start watching anything at the location of the initial watch.

**Comment by itfanr** [comment]
I watched a directory to know if it is removed, but I got :
```
Event { wd: WatchDescriptor { id: 1, fd: (Weak) }, mask: MOVE_SELF, cookie: 0, name: None }
File moved self: None
```
But it did not give me the info about the directory is moved to.

**Comment by hannobraun** [comment]
@itfanr: I'm not sure, but maybe you need to watch each file in the directory instead of or in addition to the directory itself? Check out the inotify man page: https://www.man7.org/linux/man-pages/man7/inotify.7.html

There are different event generated for directories (`IN_MOVED_FROM` and `IN_MOVED_TO`) and files (`IN_MOVE_SELF`). Maybe the `IN_MOVE_SELF` for the file is more useful.

**Comment by itfanr** [comment]
@hannobraun  Thank you. I have to watch the parent directory to get the info I want.
